### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by lilxamz** [greeninja/fictional-computing-machine#26]
Tables are not currently labelled correctly, the agents listed at the bottom do not match the data that is shown. They might need to be displayed one on top of the other rather than side to side to enable enough room for all the data to be displayed.

**Comment by greeninja** [comment]
Thought changing to Bars would fix this but it hasn't. Will look at the CSS at a later point to see if the graph height can be extended to accommodate larger teams.

**Comment by lilxamz** [comment]
It has worked for the separate teams, just not for the whole team
